### PR TITLE
Grant INTERNET, ACCESS_NETWORK_STATE permissions

### PR DESCRIPTION
**Pull request by matan129**
_Might_ solve #6 and [my own thread here](https://groups.google.com/u/1/g/tasker/c/1hYPrHJxZFQ).

The idea is to make Tasker Settings ask for the _permanent_ "Change WiFi Connectivity permission" under MIUI specifically.

According to this random Chinese article, the two permissions I added might just be the missing ones.
https://blog.csdn.net/u014632228/article/details/101207983

I tried to verify it by myself but when building locally, I couldn't install the APK because of some package conflict (I guess that because TaskerSettings interferes somehow with the Tasker package, and I can't sign on @joaomgcd's behalf 🙂).

### CODE REVIEW

**Comment by joaomgcd** [comment]
Hi! Thanks for the request! :) Did you try it out? Does it make it work?

**Comment by matan129** [comment]
I tried to, but as stated - 
> I tried to verify it by myself but when building locally, I couldn't install the APK because of some package conflict (I guess that because TaskerSettings interferes somehow with the Tasker package, and I can't sign on @joaomgcd's behalf 🙂).

**Comment by joaomgcd** [comment]
Oh, you're right :) Ok, I've built it with the permission. Can you please try it?

https://drive.google.com/open?id=1B_cVPKDvIWQPmr3ZppymGvAKEinLsukc&authuser=joaomgcd%40gmail.com&usp=drive_fs

**Comment by matan129** [comment]
Hi, thanks. I tried it and it didn't work - the app still doesn't seem to request that permission.

If you have other ideas I'd love to hear about it and test on my device.

An interesting direction here is that Tasker itself (not TaskerSettings) **does** request that "Change WiFI permanently" permission - so maybe if you could try to figure out what causes Tasker to have that permission...

**Comment by joaomgcd** [comment]
Tasker itself can't ask for that permission because Android doesn't allow apps that target API 29 and above to toggle wifi :) That's why Tasker Settings exists in the first place. 

Usually there's a system setting somewhere though where you can permanently give that permission so that the popup doesn't show up anymore... Can you maybe find that?

**Comment by matan129** [comment]
I feel like we're having a circular discussion (forgive me, lol). Let me sum everything up so it'll be super clear  🙂 

1. I _have_ found that system setting in which you can permanently give apps WiFi permissions. It looks like so: 

2. As you can see, that activity shows a list of apps. Some of them were given that permission (green checkmark), some not (gray question mark). The apps with the gray question mark will prompt for user confirmation when toggling WiFi. Those with the green check mark will not.

3. This is the important bit - **<ins>only some of the installed apps show on that list</ins>**. Not all of them. For our purposes:
  * Tasker does appear in that list. As you have mentioned, it's useless because of the API levels thing.
  * TaskerSettings <ins>does not</ins> appear on that list. This means that I can't give it the desired permission.

4. Therefore, the point of the PR and discussion is to figure out how to make TaskerSettings appear in that list. 🤞

**Comment by joaomgcd** [comment]
Oh, sorry😅 My bad! I have so many emails to respond to that I end up confusing them sometimes, sorry about that!

Ok, could you please try building an app (any app) with all these permissions and see if that shows up on that list? That way we at least know that it's a permission issue.

If it does show up then you can try removing some until it disappears from the list and that way we know which permission it needs.

Thank you! :)

<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
    <uses-permission android:name="android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND" />
    <uses-permission android:name="android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND" /> 
    <uses-permission android:name="android.permission.BODY_SENSORS" /> 
    <uses-permission android:name="android.permission.WRITE_CALL_LOG" />
    <uses-permission android:name="android.permission.READ_CALL_LOG" />
    <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="com.latedroid.juicedefender.permission.CONTROL_JUICEDEFENDER" />
    <uses-permission android:name="com.latedroid.juicedefender.permission.TOGGLE_MOBILE_DATA" />
    <uses-permission android:name="android.permission.MODIFY_PHONE_STATE" /> 
    <uses-permission android:name="com.android.phone.CHANGE_NETWORK_MODE" />
    <uses-permission android:name="android.permission.SET_TIME_ZONE" />
    <uses-permission android:name="android.permission.WRITE_SYNC_SETTINGS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.WRITE_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="com.android.alarm.permission.SET_ALARM" />
    <uses-permission android:name="android.permission.EXPAND_STATUS_BAR" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SET_WALLPAPER" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" /> 
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
    <uses-permission android:name="android.permission.DUMP" />
    <uses-permission android:name="android.permission.CHANGE_CONFIGURATION" />
    <uses-permission android:name="android.permission.TETHER_PRIVILEGED" />
    <uses-permission android:name="com.joaomgcd.taskersettings.SET_SETTING" />
    <uses-permission android:name="android.permission.ANSWER_PHONE_CALLS" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
    <uses-permission android:name="android.permission.NFC" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.REQUEST_DELETE_PACKAGES" />
    <uses-permission android:name="android.permission.SET_MEDIA_KEY_LISTENER" />
    <uses-permission android:name="android.permission.SET_WALLPAPER_COMPONENT" /> 
    
    <uses-permission android:name="android.permission.RESTART_PACKAGES" /> 
    <uses-permission android:name="android.permission.KILL_BACKGROUND_PROCESSES" /> 
    <uses-permission android:name="android.permission.ACCESS_WIMAX_STATE" /> 
    <uses-permission android:name="android.permission.CHANGE_WIMAX_STATE" /> 
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
    <uses-permission android:name="android.permission.READ_CLIPBOARD_IN_BACKGROUND" />
    <uses-permission android:name="android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER" />
    <uses-permission android:name="android.permission.READ_LOGS" />
    <uses-permission
        android:name="android.permission.SET_PROCESS_LIMIT"
        tools:ignore="ProtectedPermissions" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="com.wireguard.android.permission.CONTROL_TUNNELS" />
    <uses-permission android:name="com.termux.permission.RUN_COMMAND" />
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission
        android:name="android.permission.QUERY_ALL_PACKAGES"
        tools:ignore="QueryAllPackagesPermission" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission
        android:name="android.permission.MANAGE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />
    <uses-permission android:name="android.permission.CALL_COMPANION_APP" /> 
    <uses-permission android:name="android.permission.INTERACT_ACROSS_USERS" />
    <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
    <uses-permission android:name="moe.shizuku.manager.permission.API_V23" />

**Comment by joaomgcd** [comment]
Hi again! :) Were you able to give my suggestion a try?

**Comment by AdmiralStipe** [comment]
Any progress on this? I find it extremely annoying to connect and run ADB command after every restart on my Xiami phone and I'm keen on giving this solution a try...

**Comment by matan129** [comment]
Not yet. What adb command do you use?

**Comment by AdmiralStipe** [comment]
Sorry for not being clear - I use adb tcpip 5555 to activate ADB Wifi after every restart (and use ADB Wifi for toggling Wifi), but it's too annoying to do that all the time. Therefore I'm interested in this solution as it will get rid of additional Xiaomi confirmation when toggling Wifi with Tasker settings, if I understood correctly...

**Comment by AdmiralStipe** [comment]
> Hi. This is not related to that issue. For ADB Wifi you do need to re-run it on every boot, sorry!

Yes, I'm aware it's not related. What I was trying to tell is, that at the moment I'm forced to use ADB Wifi (which I don't like for the reasons stated), as on my MIUI I have the same problem as matan129 (additional confirmation) when using TaskerSettings for WiFi toggle. This issue (and not ADB Wifi)  could be solved with this PR, if I understood correctly. That's the reason I was asking about progress, not because of ADB Wifi. :)

**Comment by Extremedaneben** [comment]
Hello,
At the moment I am using poco X3 nfc with miui 13.02 / android 12.
Before the update it was working fine with miui 12.5.7 / android 11 and the Tasker settings app.

Now i have tested all available Tasker settings versions regular on git, include the testing one here. 
Before v1.2 an error appears (toggle wifi api29...) 
Since v1.2 it appears on the list for toggle wifi right management.
Since v1.3 it want to have location always permission.
IMG_20221026_134336
IMG_20221026_134549

But nevertheless with all through Android reachable permissions enabled I will get this pop-up message every time Tasker wants to toggle wifi.
IMG_20221026_134456

This should appear with all Tasker settings versions since 1.2 on miui 13 with android 12.

**Comment by matan129** [comment]
@Extremedaneben, the permission you show is very similar to the one I'm referring to originally, but not the same.

The one you mentioned (in which Tasker Settings does appear) is accessed via `Settings -> Privacy Protection -> Special Permissions -> WiFi Control` (or the equivalent German terms...).

The problematic permission is at `Settings -> Privacy Protection -> Other Permissions -> Change Wi-F- connectivity` - in that list, Tasker settings doesn't appear.

**Comment by matan129** [comment]
@joaomgcd OK, so this is going to be a bummer... it seems that it's (surprise) the `targetSdkVersion`. Bah.

Changing it to `23` (or above) makes MIUI show that permission. Also, the extra `ACCESS_NETWORK_STATE`, `INTERNET` permissions are not needed.

The question is if this makes this whole thing moot. If I understand correctly - any API version under 29 should be okay Wi-Fi wise, am I right? In other words - can we change `targetSdkVersion` to `23`?

**Comment by joaomgcd** [comment]
Unfortunately we can't, sorry :( target 21 is needed for some settings to be changeable with the **Custom Setting** action... That's why it's stuck on that level in the first place...

I would need to create a separate Tasker Settings app for Wifi and another one for Custom Setting... This whole thing is a mess😭

**Comment by matan129** [comment]
It ain't that bad... These APK(s) are not really distributed by Google Play, you just have to build them on github and that's it basically, right?

Also, do mind maybe compiling the apk again from my branch with your signature so I could really see if it works locally? 😁

**Comment by joaomgcd** [comment]
Ok, here's a version with target API set to 23: https://drive.google.com/open?id=1xIdu09lnmuuau4SpkAKZOYWKtE6HWe2Y&authuser=joaomgcd%40gmail.com&usp=drive_fs

Does that work?

**Comment by 2kva** [comment]
Works for me, MIUI Global 13.0.5.0

**Comment by matan129** [comment]
Yep, works for me as well. MIUI Global 13.0.4 on Poco F3.

**Comment by Extremedaneben** [comment]
Can confirm it, too.
Miui 13 with android 12

**Comment by AdmiralStipe** [comment]
Yaaay, works for me too, MIUI Global 13.0.4 on Redmi Note 11 Pro+ :) .

**Comment by cript0n2112** [comment]
Working for me too on latest xiaomi.eu Stable Miui13! Many thanks!

**Comment by joaomgcd** [comment]
Ok, I've added a special target API 23 APK to the release here: https://github.com/joaomgcd/TaskerSettings/releases/tag/v1.4.0

Hope this helps everyone else out :)

**Comment by matan129** [comment]
@joaomgcd thanks a lot!
Maybe add a note about Xiaomi devices? (Not just Huawei) + link to this discussion for future reference

**Comment by joaomgcd** [comment]
Ok, added! :) Thanks again for your help!!

**Comment by AdmiralStipe** [comment]
Anyone else having the same issue again since updating to MIUI14? It used to work perfectly before, but now I get the confirmation dialog again at every Wi-Fi toggle attempt from Tasker...

**Comment by matan129** [comment]
I'm on Poco F3, which haven't yet got MIUI14 🤔

**Comment by AdmiralStipe** [comment]
Seems that I'm an early bird concerning updates... which sucks, as I'm always the first one to run it into new troubles :). 

I'm curious, would raising target API for a couple of digits solve also this instance (MIUI14 involves updating to Android13 from Android12, so I guess the target API has something to do with it)...

**Comment by AdmiralStipe** [comment]
Noone else? @joaomgcd , is it feasible to expect a new Tasker Settigns version with increased Target API (if that's the solution)?

**Comment by vedranb7** [comment]
@AdmiralStipe here's the solution, I've been trying to fix it right now and finally did it.
After installing Tasker settings 1.5 xiaomi edition from joao's releases, go to apps - Manage apps - Tasker settings - Other permissions - set Change wifi connectivity to "Always allow".

**Comment by AdmiralStipe** [comment]
> After installing Tasker settings 1.5 xiaomi edition from joao's releases, go to apps - Manage apps - Tasker settings - Other permissions - set Change wifi connectivity to "Always allow".

Thx for the tip, but I already did that (multiple times, also tried to disable and enable it again, reinstalled 1.4.0 and 1.5.0 again), but with no success. I still get the confirmation pop-up when trying to tofgle Wi-Fi :( .

**Comment by joaomgcd** [comment]
> Noone else? @joaomgcd , is it feasible to expect a new Tasker Settigns version with increased Target API (if that's the solution)?

Unfortunately keeping the API level low is what keeps Tasker Settings working, so updating that would defeat its purpose altogether, sorry!

**Comment by matan129** [comment]
> Anyone else having the same issue again since updating to MIUI14? It used to work perfectly before, but now I get the confirmation dialog again at every Wi-Fi toggle attempt from Tasker...

Updated to MIUI 14 (Android 13) on Poco F3. The modified TaskerSettings works for me 🤷

**Comment by icantremember** [comment]
Having a similar issue with my Sony Xperia 1 mark iii on Android 13. Using a profile/task combo that I've been using for years on other phones, including a Pixel on 13. I get the following popup when trying to re-enable wi-fi in a task 
PLDhlSQ

I've tried Tasker Settings 1.2.0, 1.5.0, and the Huami/Xiaomi 1.5.0 with no success.

**Comment by icantremember** [comment]
Would the license-manager version that doesn't require the separate Tasker Settings apk help at all?

**Comment by sp4rkie** [comment]
> Unfortunately I don't know if there's a way to prevent that one, sorry! :(

When trying to activate Wi-Fi within a tasker action on my new "Jelly-Star" Android13 phone I've  got the same "ALLOW" popup .

All I  had to do is to just insert an 'AutoInput Action v2' with "click(text,ALLOW)".
Since that all works like a charm again, with a fully automated Popup answer after switching on Wi-Fi.

Isn't that the answer to the problems mentioned in this thread?

BTW: thanks for all your excellent work:-)

**Comment by icantremember** [comment]
> All I had to do is to just insert an 'AutoInput Action v2' with "click(text,ALLOW)".

Interesting... does that work if the screen is locked?

**Comment by sp4rkie** [comment]
I wasn't aware of the fact, that the 'lock screen' obviously is  a required condition to trigger the problem. I tried to reproduce and indeed, my suggestion above only works if the screen is not locked.

to solve the 'lock screen' variant of the problem I simply select the option settings->network&internet->Internet->network preferences->turn on Wi-Fi automatically

this of course works even with active lock screen since tasker is not involved at all in this case.

**Comment by andiukas** [comment]
The problem is not solved, same problem with 1.7.1 version

**Comment by CandidB** [comment]
I tested both TaskerSettings 1.4.0 and 1.7.1 the normal and the Huawei/Xiaomi version. But with all of them I get the Allow-Message, when I want to turn wifi on/off.

**Comment by joaomgcd** [comment]
Sorry, if there's not a setting to turn that off, there's nothing I can do. Tasker doesn't create that popup itself.

**Comment by CandidB** [comment]
Yes, I know. Because there are different versions I thought a special Xiaomi edition would be possible. Thank you for responding!

**Comment by EduMong** [comment]
> Ok, here's a version with target API set to 23: https://drive.google.com/open?id=1xIdu09lnmuuau4SpkAKZOYWKtE6HWe2Y&authuser=joaomgcd%40gmail.com&usp=drive_fs
> 
> Does that work?

**Comment by EduMong** [comment]
Hope you fine....Can you help me sort out my loan phone....is there any app that can delete out all the information about the phone on credit given to me?

**Pull request closed without merging**
